export const firstName = '#first-name'
export const lastName = '#last-name'
export const postCode = '#postal-code'
export const continueButton = '#continue'
export const priceProduct = '.inventory_item_price'
export const totalPrice = '.summary_total_label'
